/* GENERATED by _src/build.js from _src/docs.js — do not edit by hand. */

export const DOCS = [
  {
    "id": "msds-sn180",
    "kind": "MSDS",
    "code": "SN-180",
    "title": "Base Oil SN-180",
    "sub": "Material Safety Data Sheet",
    "key": "msds-base-oil-sn-180.pdf",
    "pages": 3,
    "bytes": 4888421,
    "origin": "Turkmenistan"
  },
  {
    "id": "msds-sn350",
    "kind": "MSDS",
    "code": "SN-350",
    "title": "Base Oil SN-350",
    "sub": "Material Safety Data Sheet",
    "key": "msds-base-oil-sn-350.pdf",
    "pages": 2,
    "bytes": 497012,
    "origin": "Turkmenistan"
  },
  {
    "id": "msds-sn600",
    "kind": "MSDS",
    "code": "SN-600",
    "title": "Base Oil SN-600",
    "sub": "Material Safety Data Sheet",
    "key": "msds-base-oil-sn-600.pdf",
    "pages": 2,
    "bytes": 939543,
    "origin": "Turkmenistan"
  },
  {
    "id": "tds-base-oil",
    "kind": "TDS",
    "code": "RANGE",
    "title": "Base Oil — full range",
    "sub": "Technical Data Sheet",
    "key": "tds-base-oil-range.pdf",
    "pages": 1,
    "bytes": 396549,
    "origin": "Turkmenistan"
  },
  {
    "id": "pp-turkmenplen",
    "kind": "SPEC",
    "code": "TURKMENPLEN",
    "title": "Polypropylene — Turkmenplen",
    "sub": "Origin & grade specification",
    "key": "spec-polypropylene-turkmenplen.pdf",
    "pages": 1,
    "bytes": 453147,
    "origin": "Turkmenistan"
  }
];

export const DOC_BY_ID = Object.fromEntries(DOCS.map((d) => [d.id, d]));
