const fs = require('fs');
const path = require('path');

const KCSS = require('./kernel-css');
const KJS = require('./kernel-js');
const { gul, header, footer, chrome, loader } = require('./shell');

const OUT = '/Users/Shreyash/Desktop/Globalex/globalex.me';
const HERE = __dirname;

const FONTS = 'https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,400..900&family=Instrument+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap';
const THREE_CDN = 'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js';

// The logo is white-on-transparent, so it also gets served on the brand plate
// for light browser chrome — same file, unmodified, just composited.
const LOGO_B64 = fs.readFileSync(path.join(OUT, 'assets/logo.webp')).toString('base64');
const faviconPlate = 'data:image/svg+xml,' + encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 70 70">`
  + `<rect width="70" height="70" fill="#04121A"/>`
  + `<image xlink:href="data:image/webp;base64,${LOGO_B64}" x="2" y="7" width="66" height="56"/>`
  + `</svg>`
);

function render(p) {
  const three = p.three ? `<script src="${THREE_CDN}"></script>\n` : '';
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<meta name="theme-color" content="#04121A" />
<meta name="color-scheme" content="dark" />
<title>${p.title}</title>
<meta name="description" content="${p.desc}" />
<meta property="og:title" content="${p.title}" />
<meta property="og:description" content="${p.desc}" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Globalex Trading DMCC" />
<link rel="icon" type="image/svg+xml" href="${faviconPlate}" />
<link rel="alternate icon" type="image/webp" href="assets/logo.webp" />
<link rel="apple-touch-icon" href="assets/logo.webp" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="${FONTS}" rel="stylesheet" />
<style>${KCSS}${p.css || ''}</style>
</head>
<body data-page="${p.page}">

${loader}
${chrome}
<a class="skip" href="#main">Skip to content</a>

${header(p.page)}

<main id="main">
${p.body}
</main>

${footer()}

${three}<script>${KJS}</script>
${p.js ? `<script>${p.js}</script>` : ''}
</body>
</html>
`;
}

/* The Worker cannot require() out of _src, so emit an ESM copy of the
   catalogue it can import. One source of truth, no drift between what the
   page offers and what the backend will serve. */
function emitDocCatalogue() {
  const { DOCS } = require('./docs');
  const slim = DOCS.map((d) => ({
    id: d.id, kind: d.kind, code: d.code, title: d.title, sub: d.sub,
    key: d.key, pages: d.pages, bytes: d.bytes, origin: d.origin,
  }));
  const out = path.join(OUT, 'functions/_lib/docs.js');
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(
    out,
    `/* GENERATED by _src/build.js from _src/docs.js — do not edit by hand. */\n\n` +
      `export const DOCS = ${JSON.stringify(slim, null, 2)};\n\n` +
      `export const DOC_BY_ID = Object.fromEntries(DOCS.map((d) => [d.id, d]));\n`
  );
  console.log(`  functions/_lib/docs.js  ${slim.length} document(s)`);
}
emitDocCatalogue();

/* The dashboard is an app, not a marketing page — it takes none of the site
   chrome, so it gets its own minimal shell rather than render(). */
function emitAdmin() {
  const a = require('./admin');
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="theme-color" content="#04121A" />
<meta name="color-scheme" content="dark" />
<title>Control — Globalex Trading DMCC</title>
<link rel="icon" type="image/svg+xml" href="${faviconPlate}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="${a.FONTS}" rel="stylesheet" />
<style>${a.css}</style>
</head>
<body>
${a.body}
<script>${a.js}</script>
</body>
</html>
`;
  const out = path.join(OUT, 'admin.html');
  fs.writeFileSync(out, html);
  console.log(`  admin.html  ${(fs.statSync(out).size / 1024).toFixed(0)} KB`);
}

const files = fs.readdirSync(path.join(HERE, 'pages')).filter((f) => f.endsWith('.js'));
let n = 0;
for (const f of files) {
  const mod = require(path.join(HERE, 'pages', f));
  const out = path.join(OUT, `${mod.page}.html`);
  fs.writeFileSync(out, render(mod));
  const kb = (fs.statSync(out).size / 1024).toFixed(0);
  console.log(`  ${mod.page}.html  ${kb} KB`);
  n++;
}
emitAdmin();
console.log(`\n${n + 1} page(s) written.`);
